In [110]:
"""Numpy 1.What is Numpy?
Numpy is a powerful library in Python used for numerical computing. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures efficiently.
How are lists different from Numpy?
Lists are general-purpose containers that can hold elements of different data types, while Numpy arrays are specifically designed for numerical data and provide better performance for mathematical operations due to their fixed data type and optimized memory usage.
Numpy is faster than lists because it uses contiguous memory allocation and vectorized operations, which reduce the overhead of looping in Python.
numpy is fixed type whereas lists are heterogeneous.
No type checking when iterating thrrough objects in numpy 
Applications of Numpy:
1. Data Analysis: Numpy is widely used in data analysis for handling large datasets and performing statistical operations.
2. Scientific Computing: Numpy is essential in scientific computing for simulations, numerical modeling, and solving mathematical problems.
3. Machine Learning: Numpy is often used in machine learning for data preprocessing, feature extraction, and implementing algorithms.
4.mathematics: Numpy provides a wide range of mathematical functions for linear algebra, calculus, and other mathematical operations.
plotting (like matplotlib)
backend (like pandas,connect 4 , digital photography)

"""

'Numpy 1.What is Numpy?\nNumpy is a powerful library in Python used for numerical computing. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures efficiently.\nHow are lists different from Numpy?\nLists are general-purpose containers that can hold elements of different data types, while Numpy arrays are specifically designed for numerical data and provide better performance for mathematical operations due to their fixed data type and optimized memory usage.\nNumpy is faster than lists because it uses contiguous memory allocation and vectorized operations, which reduce the overhead of looping in Python.\nnumpy is fixed type whereas lists are heterogeneous.\nNo type checking when iterating thrrough objects in numpy \nApplications of Numpy:\n1. Data Analysis: Numpy is widely used in data analysis for handling large datasets and performing statistical operations.\n2. Scientific Computing: Numpy is essential in scientific c

In [111]:
#load numpy
import numpy as np


In [112]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [113]:
b = np.array([[0.3, 5.5],[3.3, 5.6]])#2D array
print(b)

[[0.3 5.5]
 [3.3 5.6]]


In [114]:
#we can place list in list to create 2D array
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [115]:
#get dimension
print(a.ndim)  # Output: 2


1


In [116]:
#get shape
print(c.shape) # rows and colunms # Output: (3, 3)

(3, 3)


In [117]:
#get type
print(type(a))  # Output: <class 'numpy.ndarray'>
a.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [118]:
#get size
b.itemsize

8

In [119]:
#get total size
c.nbytes

36

In [120]:
#accessing or changing elements ,rows,colunms etc..
A = np.array([[1,2,3,4,5,6,7,8,9],[2,4,6,8,0,3,7,9,5]])
print(A)
A.shape

[[1 2 3 4 5 6 7 8 9]
 [2 4 6 8 0 3 7 9 5]]


(2, 9)

In [121]:
#get specific element [r,c]
print(A[1,4]) #0   row -1 ,colunm -4
#negative indexing
print(A[-1,-7]) #6 row -1 ,colunm -7



0
6


In [122]:
#get specific row
print(A[0,:]) #first row

[1 2 3 4 5 6 7 8 9]


In [123]:
#get speciifc colunm
print(A[:,2]) #third colunm means index 2 

[3 6]


In [124]:
a#getting a little more fancy [startindex:endindex:stepsize]
print(A[0,1:8:2]) #row 0 ,colunm from index 1 to 7 with stepsize 2
#output : [2 4 6 8]
print(A[1,::3]) #row 1 ,all colunms with stepsize 3
#output : [2 8 7]


[2 4 6 8]
[2 8 7]


In [125]:
#changing elements
A[1,4] = 20 #changing specific element
print(A)
A[:,2] = [1,2] #changing entire colunm
print(A)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 20  3  7  9  5]]
[[ 1  2  1  4  5  6  7  8  9]
 [ 2  4  2  8 20  3  7  9  5]]


In [126]:
# 3D exaple
D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(D)
D.shape
D[0,1,1]  # accessing element 4
D[:,1,:]  # accessing specific slice
D[:, :, 1]  # accessing specific slice
D[:, :, 0]  # accessing specific slice
D[:, :, 0] = [[9, 8], [7, 6]]  # changing specific slice
print(D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[9 2]
  [8 4]]

 [[7 6]
  [6 8]]]


In [127]:
#All 0's matrix
np.zeros((2,3)) #2 rows ,3 colunms


array([[0., 0., 0.],
       [0., 0., 0.]])

In [128]:
#All 1's matrix
np.ones((3,4)) #3 rows ,4 colunms


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [129]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [130]:
#when copying arrays!!!
E = np.array([1,2,3])
F = E.copy()
print(F)



[1 2 3]


In [131]:
#randome decimal numbers
np.random.rand(2,3) #2 rows ,3 colunms
np.random.randint(1,100,size=(3,4)) #randome integers between 1 to 100 of size 3 rows and 4 colunms
print(np.random.randint(1,100,size=(3,4)))

[[64 98 78 93]
 [73 87 57 12]
 [13 15 12  8]]


In [133]:
x = np.array([1,2,3,4,5])
print(x)
x += 2 #adding 2 to each element
print(x)
x - 2 #subtracting 2 from each element
print(x)
x * 5 #multiplying each element by 5
print(x)
x / 7 #dividing each element by 3
print(x)
x // 4 #floor division of each element by 2
print(x)
x ** 7 #raising each element to the power of 2
print(x)



[1 2 3 4 5]
[3 4 5 6 7]
[3 4 5 6 7]
[3 4 5 6 7]
[3 4 5 6 7]
[3 4 5 6 7]
[3 4 5 6 7]


In [134]:
#linear algebra
y = np.array([[1,2],[3,4]])
z = np.array([[5,6],[7,8]])
print(y)
print(z)
np.matmul(y,z)  #matrix multiplication



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [135]:
## Find the determinant
c = np.identity(3) #3x3 identity matrix
np.linalg.det(c)# 1.0

1.0

In [ ]:
#Statistics 
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
np.min(stats)

1

In [138]:
np.max(stats, axis=1)

array([3, 6])

In [139]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [140]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [141]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [142]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
""" were we can load datasets and using numpy ,mathplotlib we can make visual graphical representations .cache.
were numpy has more built in functions and methods to make our work easier and faster ."""